# https://typescript-eslint.io/docs/linting/
root: true
env:
  node: true
  es2022: true
  browser: true
parser: '@typescript-eslint/parser'
plugins:
  - import
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: latest
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
        - tsconfig.node.json
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
