root: true
env:
  node: true
  es2021: true
  browser: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parserOptions:
  sourceType: module
  project: tsconfig.json
  ecmaVersion: latest
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json
rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': off
